development:
  adapter: mysql2
  database: ford_development
  username: root
  password:
  host: localhost
test:
  adapter: mysql2
  database: ford_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql2
  database: ford_production
  username: root
  password: 
  host: localhost